# Generated by Django 4.1.2 on 2022-10-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='rent',
            field=models.TextField(blank=True),
        ),
    ]
