# Generated by Django 4.1.2 on 2022-10-24 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_car_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='rent',
        ),
    ]
