# Generated by Django 4.1.2 on 2022-10-26 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_alter_employee_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='rent',
        ),
    ]
